spring:
  profiles:
    active: development
  application:
    name: API-gateway
  cloud:
    gateway:
      routes:
      - id: Restaurant-M-S
        predicates:
        - Path=/Restaurant-M-S/**
        filters:
        - StripPrefix=1
        - AuthenticationFilter
        uri: ${services.url.restroverse}
      - id: Restaurant-M-S
        predicates:
          - Path=/Restaurant-M-S/**
        filters:
          - StripPrefix=1
          - AuthenticationFilter
        uri: ${services.url.inventory}

jwt:
  tokenSecret: 926D96C90030DD58429D2751AC1BDBBC

---
spring:
  config:
    activate:
      on-profile: development

server:
  port: 5002


services:
  url:
    Restaurant-M-S: http://localhost:5000




